### PR TITLE
Higher res images and faster api responses.

### PR DESCRIPTION
**Pull request by overcyn**
Does this work?

### CODE REVIEW

**Comment by kevinahn7** [comment]
I am getting this error:

Failed to load http://aspnetplayground20180909102606.azurewebsites.net/home/pokemon/1/: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:4200' is therefore not allowed access.

I tried changing it to a https and I am still getting this error

**Comment by kevinahn7** [comment]
I do like those images better though, were you able to get it working on your end?

**Comment by overcyn** [comment]
I haven't tried running this project so not sure.

**Comment by overcyn** [comment]
Try again now?

**Comment by kevinahn7** [comment]
image

**Comment by kevinahn7** [comment]
has the right source, but the png image wont populate

**Pull request closed without merging**
